SOURCES= img_algorithm.cpp 	\
	img_color.cpp 		\
	img_depend.cpp 		\
	img_draw.cpp 		\
	img_escala.cpp		\
	img_iterator2D.cpp

INCS= img.h 			\
    img_image.h		\
    img_iterator2D.h	\
    img_color.h			\
    img_algorithm.h		\
    img_draw.h			\
    img_escala.h 		\
    img_view.h 			\
    img_grid.h 			\
    img_test.h


# NOMBRE DE LA BIBLIOTECA
LIB=img

include $(IMG_COMPRULES)


